config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "www.pettp.com"
  root to: 'pages#home'
  devise_for :admins, controllers: { registrations: 'admins/registrations' }
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resource :pet
  end
  resources :admins do
    resource :profile
  end
  resources :conversations do
    resources :messages
  end
  get 'pets', to: 'users#petindex'
  get 'pets/:id' , to: 'users#petshow'
  get 'verification', to: 'users#verification'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :reports
  get 'rules', to: 'pages#rules'
  get '/admins/sign_up' => redirect('pages#home')
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar,
                    :styles => { :medium => "300x300", :thumb => "100x100" },
                    :default_url => "images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :description, length: { maximum: 500,
    too_long: "%{count} characters is the maximum allowed for descriptions." }, 
    obscenity: true
  validates :neoname, length: { maximum: 20,
    too_long: "%{count} characters is the maximum allowed for Neopets Usernames." }, 
    obscenity: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:edit, :update]
  before_action :only_current_user
  skip_before_action :only_current_user, only: [:edit, :update]
  
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
    @profile = Profile.new
  end
  
  # POST to /users/:user_id/profile
  def create
    # Ensure that we have the user or admin who is filling out form
    @user = User.find( params[:user_id] )
    # Create profile linked to this specific user or admin
    @profile = @user.build_profile( profile_params )
    if @profile.save
      flash[:success] = "Profile updated!"
      redirect_to user_path( params[:user_id] )
    else
      flash[:danger] = @profile.errors.full_messages.join(", ")
      render action: :new
    end
  end
  
  #GET to /users/:user_id/profile/edit
  def edit
    @user = User.find( params[:user_id] )
    @profile = @user.profile
  end
  
  #PUT to /users/:user_id/profile/
  def update
    #Retrieve user from database
    @user = User.find( params[:user_id] )
    #Retrieve user's profile
    @profile = @user.profile
    #Mass assign edited profile attributes and save (update)
    if @profile.update(profile_params)
      flash[:success] = "Profile updated!"
      #Redirect user to profile page
      redirect_to user_path(id: params[:user_id] )
    else 
      flash[:danger] = @profile.errors.full_messages.join(", ")
      render action: :edit
    end
  end
  
  private
    def profile_params
      params.require(:profile).permit(:description, :neoname)
    end
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end
end

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    Neopets Username (Optional):
    <%= f.text_field :neoname, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>: Use this to explain about the pets, what you're seeking, etc.
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<% if user_signed_in? || admin_signed_in? %>
  <% if admin_signed_in? || current_user.id == @profile.user.id %>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1 class="text-center">Edit your Profile</h1>
          <p class="text-center">Need a change?  Do so here.</p>
          <div class="well">
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">People won't be able to see what pets you have until you do so!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>