config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "www.pettp.com"
  root to: 'pages#home'
  devise_for :admins, controllers: { registrations: 'admins/registrations' }
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resource :pet
  end
  resources :admins do
    resource :profile
  end
  resources :conversations do
    resources :messages
  end
  get 'pets', to: 'users#petindex'
  get 'pets/:id' , to: 'users#petshow'
  get 'verification', to: 'users#verification'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :reports
  get 'rules', to: 'pages#rules'
  get '/admins/sign_up' => redirect('pages#home')
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  validates_presence_of :name, :species, :color
  validates :description, length: { maximum: 500,
    too_long: "%{count} characters is the maximum allowed for descriptions." }, 
    obscenity: true
  validates :agreement, acceptance: true
  validates :name, uniqueness: {message: "Opps, this pet is already in the database!"}, length: { maximum: 20,
    too_long: "%{count} characters is the maximum allowed for names." }, format: { with: /\A[a-zA-Z0-9\_]+\z/, message: "can only have numbers, letters and underscores." }, 
    obscenity: true
  
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings
  
  def tag_list
    tags.join(", ")
  end
  
  def self.namesearch(namesearch)
    where("name LIKE ?", "%#{namesearch}%") 
  end
  
  def self.rangebdsearch(minbdsearch, maxbdsearch)
   where("hsd >= ?", minbdsearch).where("hsd <= ?", maxbdsearch)
  end
  
  def self.minbdsearch(minbdsearch)
   where("hsd >= ?", minbdsearch)
  end
  
  def self.maxbdsearch(maxbdsearch)
   where("hsd <= ?", maxbdsearch)
  end
  
  def self.colorsearch(colorsearch)
    where("color LIKE ?", "%#{colorsearch}%")
  end
  
  def self.speciessearch(speciessearch)
    where("species LIKE ?", "%#{speciessearch}%")
  end
  
  def self.ucsearch(ucsearch)
    where(:uc => ucsearch != "false")
  end
  
  def self.rnrwsearch(rwsearch, rnsearch)
    where("rw = ? OR rn = ?", true, true)
  end
  
  def self.rwsearch(rwsearch)
    where(:rw => rwsearch != "false")
  end
  
  def self.rnsearch(rnsearch)
    where(:rn => rnsearch != "false")
  end
  
  def self.uftsearch(uftsearch)
    where(:uft => uftsearch != "false")
  end
  
  def self.ufasearch(ufasearch)
    where(:ufa => ufasearch != "false")
  end
  
  def self.namelengthsearch(namelengthsearch)
    length = namelengthsearch.to_i
    where("LENGTH(name) = ?", length)
  end
  
  self.per_page = 20
  
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :only_current_user
  skip_before_action :only_current_user, only: [:update]

  # GET to /users/:user_id/pet/new
  def new
    @user = User.find( params[:user_id] )
    @pet = Pet.new
  end

  # POST to /users/:user_id/pet
  def create
    # Ensure that we have the user  who is filling out form
    @user = User.find( params[:user_id] )
    # Create pet linked to this specific user or admin
    @pet = @user.pets.build( pet_params )

    # Add the other paramaters
    species_array = [['Acara', 1], ['Aisha', 2], ['Blumaroo', 3],
      ['Bori', 4], ['Bruce', 5], ['Buzz', 6], ['Chia', 7], ['Chomby', 8],
      ['Cybunny', 9], ['Draik', 10], ['Elephante', 11], ['Eyrie', 12],
      ['Flotsam', 13], ['Gelert', 14], ['Gnorbu', 15], ['Grarrl', 16],
      ['Grundo', 17], ['Hissi', 18], ['Ixi', 19], ['Jetsam', 20], ['Jubjub', 21],
      ['Kacheek', 22], ['Kau', 23], ['Kiko', 24], ['Koi', 25], ['Korbat', 26],
      ['Kougra', 27], ['Krawk', 28], ['Kyrii', 29], ['Lenny', 30], ['Lupe', 31],
      ['Lutari', 32], ['Meerca', 33], ['Moehog', 34], ['Mynci', 35],
      ['Nimmo', 36], ['Ogrin', 37], ['Peophin', 38], ['Poogle', 39],
      ['Pteri', 40], ['Quiggle', 41], ['Ruki', 42], ['Scorchio', 43],
      ['Shoyru', 44], ['Skeith', 45], ['Techo', 46], ['Tonu', 47],
      ['Tuskaninny', 48], ['Uni', 49], ['Usul', 50], ['Vandagyre', 55],
      ['Wocky', 51], ['Xweetok', 52], ['Yurble', 53], ['Zafara', 54]];

    colors_array = [['8-Bit', 92], ['Agueena', 101], ['Alien', 1], ['Apple', 2],
      ['Asparagus', 3], ['Aubergine', 4], ['Avocado', 5], ['Baby', 6], ['Biscuit', 7],
      ['Blue', 8], ['Blueberry', 9], ['Brown', 10], ['Camouflage', 11], ['Carrot', 12],
      ['Checkered', 13], ['Chocolate', 14], ['Chokato', 15], ['Christmas', 16],
      ['Clay', 17], ['Cloud', 18], ['Coconut', 19], ['Custard', 20], ['Darigan', 21],
      ['Desert', 22], ['Dimensional', 100], ['Disco', 23], ['Durian', 24],
      ['Elderlyboy', 97], ['Elderlygirl', 98], ['Electric', 25], ['Eventide', 96],
      ['Faerie', 26], ['Fire', 27], ['Garlic', 28], ['Ghost', 29], ['Glowing', 30],
      ['Gold', 31], ['Gooseberry', 32], ['Grape', 33], ['Green', 34], ['Grey', 35],
      ['Halloween', 36], ['Ice', 37], ['Invisible', 38], ['Island', 39], ['Jelly', 40],
      ['Lemon', 41], ['Lime', 42], ['Magma', 87], ['Mallow', 43], ['Maractite', 91],
      ['Maraquan', 44], ['Msp', 45], ['Mutant', 46], ['Onion', 86], ['Orange', 47],
      ['Pastel', 102], ['Pea', 48], ['Peach', 49], ['Pear', 50], ['Pepper', 51],
      ['Pineapple', 52], ['Pink', 53], ['Pirate', 54], ['Plum', 55], ['Plushie', 56],
      ['PolkaDot', 104], ['Purple', 57], ['Quigukiboy', 58], ['Quigukigirl', 59],
      ['Rainbow', 60], ['Red', 61], ['Relic', 88], ['Robot', 62], ['Royalboy', 63],
      ['Royalgirl', 64], ['Shadow', 65], ['Silver', 66], ['Sketch', 67], ['Skunk', 68],
      ['Snot', 69], ['Snow', 70], ['Speckled', 71], ['Split', 72], ['Sponge', 73],
      ['Spotted', 74], ['Starry', 75], ['Stealthy', 99], ['Strawberry', 76],
      ['Striped', 77], ['SwampGas', 93], ['Thornberry', 78], ['Tomato', 79],
      ['Transparent', 90], ['Tyrannian', 80], ['Ummagine', 103], ['UsukiBoy', 81],
      ['UsukiGirl', 82], ['Water', 94], ['White', 83], ['Woodland', 89], ['Wraith', 95],
      ['Yellow', 84], ['Zombie', 85], ['Candy', 105], ['Marble', 106],
      ['Steampunk', 107], ['Toy', 108], ['Origami', 109]];

    require 'net/http'
    require 'json'

=begin
    url = "http://www.neopets.com/amfphp/json.php/CustomPetService.getViewerData/" + @pet.name
    uri = URI(url)
    response = Net::HTTP.get(uri)
    data = JSON.parse(response)

    if data["error"]
      flash[:danger] = "That pet does not exist!"
      render action: :new
    else
      if data["custom_pet"]["biology_by_zone"]["46"]
        @pet.uc = true;
      end

      species_array.each do |species|
        id = species[1]
        if id == data["custom_pet"]["species_id"]
          @pet.species = species[0]
        end
      end

      colors_array.each do |color|
        id = color[1]
        if id == data["custom_pet"]["color_id"]
          @pet.color = color[0]
        end
      end
=end

      # so name is formatted correctly as it appears on site
      #@pet.name = data["custom_pet"]["name"]

      if @pet.hp == nil
        @pet.hp = 0
      end
      if @pet.strength == nil
        @pet.strength = 0
      end
      if @pet.defence == nil
        @pet.defence = 0
      end
      if @pet.movement == nil
        @pet.movement = 0
      end

      # set the hsd
      if @pet.strength > 750 && @pet.defence > 750
        @pet.hsd = @pet.hp + 750 + 750
      elsif @pet.strength > 750
        @pet.hsd = @pet.hp + 750 + @pet.defence
      elsif @pet.defence > 750
        @pet.hsd = @pet.hp + 750 + @pet.strength
      else
        @pet.hsd =  @pet.hp + @pet.defence + @pet.strength
      end

      if @pet.save
        flash[:success] = "Pet submitted!  It won't appear for other users until it is verified."
        redirect_to user_path( params[:user_id] )
      else
        flash[:danger] = @pet.errors.full_messages.join(", ")
        render action: :new
      end
    end

  #GET to /users/:user_id/pet/edit
  def edit
    @user = User.find( params[:user_id] )
    @pet = Pet.find_by_id( params[:id] )
  end

  #PUT to /users/:user_id/pet/
  def update
    #Retrieve user from database
    @user = User.find( params[:user_id] )
    #Retrieve user's pet
    @pet = Pet.find(params[:pet][:id])
    #Mass assign edited pet attributes and save (update)

    # Add the other paramaters
    species_array = [['Acara', 1], ['Aisha', 2], ['Blumaroo', 3],
      ['Bori', 4], ['Bruce', 5], ['Buzz', 6], ['Chia', 7], ['Chomby', 8],
      ['Cybunny', 9], ['Draik', 10], ['Elephante', 11], ['Eyrie', 12],
      ['Flotsam', 13], ['Gelert', 14], ['Gnorbu', 15], ['Grarrl', 16],
      ['Grundo', 17], ['Hissi', 18], ['Ixi', 19], ['Jetsam', 20], ['Jubjub', 21],
      ['Kacheek', 22], ['Kau', 23], ['Kiko', 24], ['Koi', 25], ['Korbat', 26],
      ['Kougra', 27], ['Krawk', 28], ['Kyrii', 29], ['Lenny', 30], ['Lupe', 31],
      ['Lutari', 32], ['Meerca', 33], ['Moehog', 34], ['Mynci', 35],
      ['Nimmo', 36], ['Ogrin', 37], ['Peophin', 38], ['Poogle', 39],
      ['Pteri', 40], ['Quiggle', 41], ['Ruki', 42], ['Scorchio', 43],
      ['Shoyru', 44], ['Skeith', 45], ['Techo', 46], ['Tonu', 47],
      ['Tuskaninny', 48], ['Uni', 49], ['Usul', 50], ['Vandagyre', 55],
      ['Wocky', 51], ['Xweetok', 52], ['Yurble', 53], ['Zafara', 54]];

    colors_array = [['8-Bit', 92], ['Agueena', 101], ['Alien', 1], ['Apple', 2],
      ['Asparagus', 3], ['Aubergine', 4], ['Avocado', 5], ['Baby', 6], ['Biscuit', 7],
      ['Blue', 8], ['Blueberry', 9], ['Brown', 10], ['Camouflage', 11], ['Carrot', 12],
      ['Checkered', 13], ['Chocolate', 14], ['Chokato', 15], ['Christmas', 16],
      ['Clay', 17], ['Cloud', 18], ['Coconut', 19], ['Custard', 20], ['Darigan', 21],
      ['Desert', 22], ['Dimensional', 100], ['Disco', 23], ['Durian', 24],
      ['Elderlyboy', 97], ['Elderlygirl', 98], ['Electric', 25], ['Eventide', 96],
      ['Faerie', 26], ['Fire', 27], ['Garlic', 28], ['Ghost', 29], ['Glowing', 30],
      ['Gold', 31], ['Gooseberry', 32], ['Grape', 33], ['Green', 34], ['Grey', 35],
      ['Halloween', 36], ['Ice', 37], ['Invisible', 38], ['Island', 39], ['Jelly', 40],
      ['Lemon', 41], ['Lime', 42], ['Magma', 87], ['Mallow', 43], ['Maractite', 91],
      ['Maraquan', 44], ['Msp', 45], ['Mutant', 46], ['Onion', 86], ['Orange', 47],
      ['Pastel', 102], ['Pea', 48], ['Peach', 49], ['Pear', 50], ['Pepper', 51],
      ['Pineapple', 52], ['Pink', 53], ['Pirate', 54], ['Plum', 55], ['Plushie', 56],
      ['PolkaDot', 104], ['Purple', 57], ['Quigukiboy', 58], ['Quigukigirl', 59],
      ['Rainbow', 60], ['Red', 61], ['Relic', 88], ['Robot', 62], ['Royalboy', 63],
      ['Royalgirl', 64], ['Shadow', 65], ['Silver', 66], ['Sketch', 67], ['Skunk', 68],
      ['Snot', 69], ['Snow', 70], ['Speckled', 71], ['Split', 72], ['Sponge', 73],
      ['Spotted', 74], ['Starry', 75], ['Stealthy', 99], ['Strawberry', 76],
      ['Striped', 77], ['SwampGas', 93], ['Thornberry', 78], ['Tomato', 79],
      ['Transparent', 90], ['Tyrannian', 80], ['Ummagine', 103], ['UsukiBoy', 81],
      ['UsukiGirl', 82], ['Water', 94], ['White', 83], ['Woodland', 89], ['Wraith', 95],
      ['Yellow', 84], ['Zombie', 85], ['Candy', 105], ['Marble', 106],
      ['Steampunk', 107], ['Toy', 108], ['Origami', 109]];

    require 'net/http'
    require 'json'

    # using params in case later we decide users can update an old pet with a different pet
=begin
    url = "http://www.neopets.com/amfphp/json.php/CustomPetService.getViewerData/" + @pet.name
    uri = URI(url)
    response = Net::HTTP.get(uri)
    data = JSON.parse(response)

    if data["error"]
      flash[:danger] = "That pet does not exist!"
      render action: :new
    else
      if data["custom_pet"]["biology_by_zone"]["46"]
        @pet.uc = true;
      else
        @pet.uc = false;
      end

      species_array.each do |species|
        id = species[1]
        if id == data["custom_pet"]["species_id"]
          @pet.species = species[0]
        end
      end

      colors_array.each do |color|
        id = color[1]
        if id == data["custom_pet"]["color_id"]
          @pet.color = color[0]
        end
      end
=end

      # so name is formatted correctly as it appears on site
      #@pet.name = data["custom_pet"]["name"]

      if @pet.update(pet_params)
        if @pet.hp == nil
          @pet.hp = 0
        end
        if @pet.strength == nil
          @pet.strength = 0

app/views/pets/_form.html.erb
<%= form_for @pet, url: user_pet_path, html: {id: 'pet_form'} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :gender %>
    <%= f.select :gender, [['Male'], ['Female']], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :species %>
    <%= f.select :species, [['Acara'], ['Aisha'], ['Blumaroo'],
      ['Bori'], ['Bruce'], ['Buzz'], ['Chia'], ['Chomby'],
      ['Cybunny'], ['Draik'], ['Elephante'], ['Eyrie'],
      ['Flotsam'], ['Gelert'], ['Gnorbu'], ['Grarrl'],
      ['Grundo'], ['Hissi'], ['Ixi'], ['Jetsam'], ['Jubjub'],
      ['Kacheek'], ['Kau'], ['Kiko'], ['Koi'], ['Korbat'],
      ['Kougra'], ['Krawk'], ['Kyrii'], ['Lenny'], ['Lupe'],
      ['Lutari'], ['Meerca'], ['Moehog'], ['Mynci'],
      ['Nimmo'], ['Ogrin'], ['Peophin'], ['Poogle'],
      ['Pteri'], ['Quiggle'], ['Ruki'], ['Scorchio'],
      ['Shoyru'], ['Skeith'], ['Techo'], ['Tonu'],
      ['Tuskaninny'], ['Uni'], ['Usul'], ['Vandagyre'],
      ['Wocky'], ['Xweetok'], ['Yurble'], ['Zafara']], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :color %>
    <%= f.select :color, [['8-Bit'], ['Agueena'], ['Alien'], ['Apple'],
      ['Asparagus'], ['Aubergine'], ['Avocado'], ['Baby'], ['Biscuit'],
      ['Blue'], ['Blueberry'], ['Brown'], ['Burlap'], ['Camouflage'], ['Candy'], ['Carrot'], 
      ['Checkered'], ['Chocolate'], ['Chokato'], ['Christmas'],
      ['Clay'], ['Cloud'], ['Coconut'], ['Custard'], ['Darigan'],
      ['Desert'], ['Dimensional'], ['Disco'], ['Durian'],
      ['Elderlyboy'], ['Elderlygirl'], ['Electric'], ['Eventide'],
      ['Faerie'], ['Fire'], ['Garlic'], ['Ghost'], ['Glowing'],
      ['Gold'], ['Gooseberry'], ['Grape'], ['Green'], ['Grey'],
      ['Halloween'], ['Ice'], ['Invisible'], ['Island'], ['Jelly'],
      ['Lemon'], ['Lime'], ['Magma'], ['Mallow'], ['Maractite'],
      ['Maraquan'], ['Marble'], ['Mosaic'], ['Msp'], ['Mutant'], ['Oil Paint'], ['Onion'], ['Orange'],
      ['Origami'], ['Pastel'], ['Pea'], ['Peach'], ['Pear'], ['Pepper'],
      ['Pineapple'], ['Pink'], ['Pirate'], ['Plum'], ['Plushie'],
      ['PolkaDot'], ['Purple'], ['Quigukiboy'], ['Quigukigirl'],
      ['Rainbow'], ['Red'], ['Relic'], ['Robot'], ['Royalboy'],
      ['Royalgirl'], ['Shadow'], ['Silver'], ['Sketch'], ['Skunk'],
      ['Snot'], ['Snow'], ['Speckled'], ['Split'], ['Sponge'],
      ['Spotted'], ['Starry'], ['Stealthy'], ['Steampunk'], ['Strawberry'],
      ['Striped'], ['SwampGas'], ['Thornberry'], ['Tomato'], ['Toy'],
      ['Transparent'], ['Tyrannian'], ['Ummagine'], ['UsukiBoy'],
      ['UsukiGirl'], ['Water'], ['White'], ['Woodland'], ['Wraith'],
      ['Yellow'], ['Zombie']], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :level %>: Level and other stats are optional
    <%= f.number_field :level, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :hp %>
    <%= f.number_field :hp, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :strength %>
    <%= f.number_field :strength, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :defence %>
    <%= f.number_field :defence, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :movement %>
    <%= f.number_field :movement, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.check_box :uc %>
    <%= f.label "Unconverted?", class: "col-md-3 align" %>
  </div>
  <br>
  <div class="form-group">
     <%= f.check_box :rw %>
    <%= f.label "Real Word?", class: "col-md-3 align" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.check_box :rn %>
    <%= f.label "Real Name?", class: "col-md-3 align" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.check_box :uft %>
    <%= f.label "Up For Trade?", class: "col-md-3 align" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.check_box :ufa %>
    <%= f.label "Up For Adoption?", class: "col-md-3 align" %>
  </div>
  <br>
  <% if admin_signed_in? %>
  <div class="form-group">
    <%= f.check_box :verified %>
    <%= f.label :verified, class: 'col-md-3 align' %>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :description %>: Seeking anything specific?  Anything special about the pet?
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <p><%= f.check_box :agreement %> I acknowledge that I have read the above
    statements and said pet is indeed UFT/UFA.</p>
  </div>
  <br/>
  <div class="form-group">
    <%= f.submit "Update Pet", class: 'btn btn-primary', id: 'form-signup-btn' %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<% if user_signed_in? || admin_signed_in? %>
  <% if admin_signed_in? || current_user.id == @pet.user.id %>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1 class="text-center">Edit <%= @pet.name %></h1>
          <p class="text-center">Use this if your pet happened to change colors, gained stats, etc.</p>
          <div class="well">
            <%= form_for @pet, url: user_pet_path, html: {id: 'pet_form'} do |f| %>
              <% if admin_signed_in? %>
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <% end %>
              <div class="form-group">
                <%= f.label :gender %>
                <%= f.select :gender, [['Male'], ['Female']], class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :species %>
                <%= f.select :species, [['Acara'], ['Aisha'], ['Blumaroo'],
                  ['Bori'], ['Bruce'], ['Buzz'], ['Chia'], ['Chomby'],
                  ['Cybunny'], ['Draik'], ['Elephante'], ['Eyrie'],
                  ['Flotsam'], ['Gelert'], ['Gnorbu'], ['Grarrl'],
                  ['Grundo'], ['Hissi'], ['Ixi'], ['Jetsam'], ['Jubjub'],
                  ['Kacheek'], ['Kau'], ['Kiko'], ['Koi'], ['Korbat'],
                  ['Kougra'], ['Krawk'], ['Kyrii'], ['Lenny'], ['Lupe'],
                  ['Lutari'], ['Meerca'], ['Moehog'], ['Mynci'],
                  ['Nimmo'], ['Ogrin'], ['Peophin'], ['Poogle'],
                  ['Pteri'], ['Quiggle'], ['Ruki'], ['Scorchio'],
                  ['Shoyru'], ['Skeith'], ['Techo'], ['Tonu'],
                  ['Tuskaninny'], ['Uni'], ['Usul'], ['Vandagyre'],
                  ['Wocky'], ['Xweetok'], ['Yurble'], ['Zafara']], class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :color %>
                <%= f.select :color, [['8-Bit'], ['Agueena'], ['Alien'], ['Apple'],
                  ['Asparagus'], ['Aubergine'], ['Avocado'], ['Baby'], ['Biscuit'],
                  ['Blue'], ['Blueberry'], ['Brown'], ['Burlap'], ['Camouflage'], ['Candy'], ['Carrot'],
                  ['Checkered'], ['Chocolate'], ['Chokato'], ['Christmas'],
                  ['Clay'], ['Cloud'], ['Coconut'], ['Custard'], ['Darigan'],
                  ['Desert'], ['Dimensional'], ['Disco'], ['Durian'],
                  ['Elderlyboy'], ['Elderlygirl'], ['Electric'], ['Eventide'],
                  ['Faerie'], ['Fire'], ['Garlic'], ['Ghost'], ['Glowing'],
                  ['Gold'], ['Gooseberry'], ['Grape'], ['Green'], ['Grey'],
                  ['Halloween'], ['Ice'], ['Invisible'], ['Island'], ['Jelly'],
                  ['Lemon'], ['Lime'], ['Magma'], ['Mallow'], ['Maractite'],
                  ['Maraquan'], ['Marble'], ['Mosaic'], ['Msp'], ['Mutant'], ['Oil Paint'], ['Onion'], ['Orange'],
                  ['Origami'], ['Pastel'], ['Pea'], ['Peach'], ['Pear'], ['Pepper'],
                  ['Pineapple'], ['Pink'], ['Pirate'], ['Plum'], ['Plushie'],
                  ['PolkaDot'], ['Purple'], ['Quigukiboy'], ['Quigukigirl'],
                  ['Rainbow'], ['Red'], ['Relic'], ['Robot'], ['Royalboy'],
                  ['Royalgirl'], ['Shadow'], ['Silver'], ['Sketch'], ['Skunk'],
                  ['Snot'], ['Snow'], ['Speckled'], ['Split'], ['Sponge'],
                  ['Spotted'], ['Starry'], ['Stealthy'], ['Steampunk'], ['Strawberry'],
                  ['Striped'], ['SwampGas'], ['Thornberry'], ['Tomato'], ['Toy'],
                  ['Transparent'], ['Tyrannian'], ['Ummagine'], ['UsukiBoy'],
                  ['UsukiGirl'], ['Water'], ['White'], ['Woodland'], ['Wraith'],
                  ['Yellow'], ['Zombie']], class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :level %>: Level and other stats are optional
                <%= f.number_field :level, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :hp %>
                <%= f.number_field :hp, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :strength %>
                <%= f.number_field :strength, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :defence %>
                <%= f.number_field :defence, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :movement %>
                <%= f.number_field :movement, class: 'form-control' %>
              </div>
              <% if admin_signed_in? %>
              <div class="form-group">
                <%= f.check_box :uc %>
                <%= f.label "Unconverted?", class: "col-md-3 align" %>
              </div>
              <br>
              <div class="form-group">
                 <%= f.check_box :rw %>
                <%= f.label "Real Word?", class: "col-md-3 align" %>
              </div>
              <br>
              <div class="form-group">
                <%= f.check_box :rn %>
                <%= f.label "Real Name?", class: "col-md-3 align" %>
              </div>
              <br>
              <% end %>
              <div class="form-group">
                <%= f.check_box :uft %>
                <%= f.label "Up For Trade?", class: "col-md-3 align" %>
              </div>
              <br>
              <div class="form-group">
                <%= f.check_box :ufa %>
                <%= f.label "Up For Adoption?", class: "col-md-3 align" %>
              </div>
              <br>
              <% if admin_signed_in? %>
              <div class="form-group">
                <%= f.check_box :verified %>
                <%= f.label :verified, class: 'col-md-3 align' %>
              </div>
              <% end %>
              <div class="form-group">
                <%= f.label :description %>: Seeking anything specific?  Anything special about the pet?
                <%= f.text_area :description, class: 'form-control' %>
              </div>
              <br/>
              <div class="form-group">
                <%= f.submit "Update Pet", class: 'btn btn-primary', id: 'form-signup-btn' %>
                <%= f.hidden_field :id, value: @pet.id %>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/pets/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if @user.profile %>
    <h1 class="text-center">Submit a Pet</h1>
    <p class="text-center"><b>ATTENTION:</b> Your pet must clearly be labeled 
    UFT/UFA on their lookup or petpage or they will not be accepted onto the site.</p>
    <p class="text-center">Your pet won't appear on the site until it is verified though</p>
    <p class="text-center"><b>NOTE: </b>If you are listing a pet UFA, you are now required 
    to entire a deadline for the pet in the description.  You pet will not be verified without a deadline.</p>
    <div class="well">
      <%= render 'form' %>
    </div>
    <% else %>
    <h1 class="text-center">Opps!</h1>
    <p class="text-center">You need to make a profile before you can submit a pet.</p>
    <% end %>
  </div>
</div>