config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "www.pettp.com"
  root to: 'pages#home'
  devise_for :admins, controllers: { registrations: 'admins/registrations' }
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resource :pet
  end
  resources :admins do
    resource :profile
  end
  resources :conversations do
    resources :messages
  end
  get 'pets', to: 'users#petindex'
  get 'pets/:id' , to: 'users#petshow'
  get 'verification', to: 'users#verification'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :reports
  get 'rules', to: 'pages#rules'
  get '/admins/sign_up' => redirect('pages#home')
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :username, :email
  validates_uniqueness_of :username, :email
  validates :terms, acceptance: true
  validates :age, acceptance: true
  validates :username, length: { maximum: 20 , too_long: "%{count} is too long, maximum is 20 characters" }, 
    format: { with: /\A[a-zA-Z0-9]+\z/, message: "can only have numbers and letters." }, obscenity: true
    
  before_destroy :destroy_everything
  
  has_one :profile
  has_many :pets
  
  def self.unamesearch(unamesearch)
    where("username LIKE ?", "%#{unamesearch}%") 
  end
         
  def email_required?
    false
  end

  def email_changed?
    false
  end
  
  self.per_page = 20
  
  private
  
  def destroy_everything
    self.pets.destroy_all
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    
end

app/controllers/users/sessions_controller.rb
class SessionsController < Devise::SessionsController

protected

  def after_sign_in_path_for(resource)
    if resource.is_a?(User) && resource.banned?
      sign_out resource
      flash[:error] = "This account has been suspended for violating the site rules."
      root_path
    else
      super
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!, only: [:verification, :edit, :update]
  
  def index
    if params[:unamesearch].present?
      @users = User.unamesearch(params[:unamesearch]).paginate(:page => params[:page]).order("id DESC")
    else
      @users = User.includes(:profile).paginate(:page => params[:page]).order("id DESC")
    end
  end
  
  #This search function is super ugly, find a way to make it nicer
  def petindex
    @users = User.includes(:pet)
    
    if params[:namesearch].present?
      @pets = Pet.namesearch(params[:namesearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:colorsearch].present? && params[:speciessearch].present?
      @pets = Pet.colorsearch(params[:colorsearch]).where(verified: true).order("created_at DESC")
      @pets = @pets.speciessearch(params[:speciessearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      if params[:ucsearch].present? && params[:uftsearch].present? && params[:ufasearch].present?
        @pets = @pets.ucsearch(params[:colorsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      elsif params[:ucsearch].present? && params[:uftsearch].present?
        @pets = @pets.ucsearch(params[:colorsearch]).where(verified: true).order("created_at DESC")
        @pets = @pets.uftsearch(params[:uftsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      elsif params[:ucsearch].present? && params[:ufasearch].present?
        @pets = @pets.ucsearch(params[:colorsearch]).where(verified: true).order("created_at DESC")
        @pets = @pets.ufasearch(params[:ufasearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      elsif params[:ucsearch].present?
        @pets = @pets.ucsearch(params[:colorsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      elsif params[:uftsearch].present?
        @pets = @pets.uftsearch(params[:uftsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      elsif params[:ufasearch].present?
        @pets = @pets.ufasearch(params[:ufasearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      end
      
    elsif params[:colorsearch].present? && params[:ucsearch].present?
      @pets = Pet.colorsearch(params[:colorsearch]).where(verified: true).order("id DESC")
      @pets = @pets.ucsearch(params[:ucsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      if params[:uftsearch].present? && params[:ufasearch].present?
        @pets = (@pets).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      elsif params[:uftsearch].present?
        @pets = @pets.uftsearch(params[:uftsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      elsif params[:ufasearch].present?
        @pets = @pets.ufasearch(params[:ufasearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      end
      
    elsif params[:colorsearch].present? && params[:uftsearch].present? && params[:ufasearch].present?
      @pets = Pet.colorsearch(params[:colorsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:colorsearch].present? && params[:uftsearch].present?
      @pets = Pet.colorsearch(params[:colorsearch]).where(verified: true).order("id DESC")
      @pets = @pets.uftsearch(params[:uftsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:colorsearch].present? && params[:ufasearch].present?
      @pets = Pet.colorsearch(params[:colorsearch]).where(verified: true).order("id DESC")
      @pets = @pets.ufasearch(params[:ufasearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:colorsearch].present?
      @pets = Pet.colorsearch(params[:colorsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:speciessearch].present? && params[:ucsearch].present?
      @pets = Pet.speciessearch(params[:speciessearch]).where(verified: true).order("id DESC")
      @pets = @pets.ucsearch(params[:ucsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      if params[:uftsearch].present? && params[:ufasearch].present?
        @pets = (@pets).where(verified: true).paginate(:page => params[:page], :per_page => 20).order("id DESC")
      elsif params[:uftsearch].present?
        @pets = @pets.uftsearch(params[:uftsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      elsif params[:ufasearch].present?
        @pets = @pets.ufasearch(params[:ufasearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      end
      
    elsif params[:speciessearch].present? && params[:uftsearch].present? && params[:ufasearch].present?
      @pets = Pet.speciessearch(params[:speciessearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:speciessearch].present? && params[:uftsearch].present?
      @pets = Pet.speciessearch(params[:speciessearch]).where(verified: true).order("id DESC")
      @pets = @pets.uftsearch(params[:uftsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:speciessearch].present? && params[:ufasearch].present?
      @pets = Pet.speciessearch(params[:speciessearch]).where(verified: true).order("id DESC")
      @pets = @pets.ufasearch(params[:ufasearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:speciessearch].present?
      @pets = Pet.speciessearch(params[:speciessearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:ucsearch].present? && params[:uftsearch].present? && params[:ufasearch].present?
      @pets = Pet.ucsearch(params[:ucsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:ucsearch].present? && params[:uftsearch].present?
      @pets = Pet.ucsearch(params[:ucsearch]).where(verified: true).order("id DESC") 
      @pets = @pets.uftsearch(params[:uftsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:ucsearch].present? && params[:ufasearch].present?
      @pets = Pet.ucsearch(params[:ucsearch]).where(verified: true).order("id DESC") 
      @pets = @pets.ufasearch(params[:ufasearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:ucsearch].present?
      @pets = Pet.ucsearch(params[:ucsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:uftsearch].present? && params[:ufasearch].present?
      @pets = Pet.includes(:user).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:uftsearch].present?
      @pets = Pet.uftsearch(params[:uftsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:ufasearch].present?
      @pets = Pet.ufasearch(params[:ufasearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:rwsearch].present? && params[:rnsearch].present?
      @pets = Pet.rnrwsearch(params[:rwsearch], params[:rnsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:rwsearch].present?
      @pets = Pet.rwsearch(params[:rwsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:rnsearch].present?
      @pets = Pet.rnsearch(params[:rnsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:minbdsearch].present? && params[:maxbdsearch].present?
      @pets = Pet.rangebdsearch(params[:minbdsearch], params[:maxbdsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:minbdsearch].present?
      @pets = Pet.minbdsearch(params[:minbdsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:maxbdsearch].present?
      @pets = Pet.maxbdsearch(params[:maxbdsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    elsif params[:namelengthsearch].present?
      @pets = Pet.namelengthsearch(params[:namelengthsearch]).where(verified: true).paginate(:page => params[:page]).order("id DESC")
      
    else
      @pets = Pet.includes(:user).where(verified: true).paginate(:page => params[:page]).order("id DESC")
    end
  end
  
  # GET to /users/:id
  def show
    @user = User.find( params[:id] )
    @pets = Pet.includes(:user)
    if user_signed_in? && current_user.id == @user.id
      @user.pets.each do |pet|
        if pet.verified == false
          flash.now[:danger] = "Looks like you have some unverified pets.  If they have been unverified for a while, 
                  make sure they're listed as UFT or UFA on their lookup!"
          break
        end
      end
    end
  end
  
  #Get to /pets/:id
  def petshow
    @pet = Pet.find( params[:id] )
  end
  
  def verification
    @users = User.includes(:pet)
    @pets = Pet.includes(:user).where(verified: false).paginate(:page => params[:page]).order("id DESC").reverse_order
  end
  
  def edit
    @user = User.find( params[:id] )
  end
  
  #PUT to /users/
  def update
    #Retrieve user from database
    @user = User.find_by_id( params[:id] )
    #Mass assign edited profile attributes and save (update)
    if @user.update(user_params)
      flash[:success] = "User updated!"
      #Redirect user to profile page
      redirect_to user_path(id: params[:id] )
    else
      flash[:danger] = @user.errors.full_messages.join(", ")
      render action: :edit

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="well">
        <h2>Edit User</h2>
        
        <%= form_for @user, url: user_path, html: { method: :put } do |f| %>
          
          <div class="field form-group">
            <%= f.label :username %><br />
            <%= f.text_field :username, class: 'form-control' %>
          </div>
          
          <div class="field form-group">
            <%= f.label "Ban user?" %><br />
            <%= f.check_box :banned, class: 'form-control' %>
          </div>
        
          <div class="actions form-group">
            <%= f.submit "Update", class: 'btn btn-success' %>
          </div>
        <% end %>
        
        <h3>Cancel my account</h3>
        
        <p>Are you sure? <%= button_to "Cancel my account", 
        user_path, data: { confirm: "Are you sure?" }, 
        method: :delete, class: 'btn btn-danger' %></p>
        
        <%= link_to "Back", :back %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">PetTP Users</h1>
      <p class="text-center">Welcome to the PetTP community.  Users must fill out a profile in order to be visible in the community.</p>
      <h3 class="text-center">Find a User</h3>
      <%= form_tag users_path, :method => :get do |f| %>
        <%= text_field_tag :unamesearch, params[:unamesearch], placeholder: "Search Username", class: 'users-inline' %>
        <%= submit_tag "Search!", :name => nil, class: 'inline' %>
      <% end %>
      <br/>
      <ul class="list-unstyled">
        <% @users.each do |user| %>
          <% if user.profile && user.banned == false %>
            <li>
              <div class="well row <%= cycle('white-bg', '') %>">
                
                <div>
                  <div class="col-sm-10">
                    <%= link_to user do %>
                      <h2 class="inline"><%= user.username %></h2>
                    <% end %>
                  </div>
                  <div class="text-center">
                    <h4 class="inline fix-margin">Pets: <%= user.pets.count %></h4>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
      <h4><%= will_paginate @users, class: 'text-center' %></h4>
      </br>
    </div>
  </div>
</div>

app/views/users/petindex.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">PetTP Pets</h1>
      <p class="text-center">Only pets that have been verified will show here.</p>
      <p class="text-center">To find a specific pet, please use the <%= link_to "home page", root_path %>.</p>
      <br/>
      <h4><%= will_paginate @pets, class: 'text-center' %></h4>
      <br>
      <ul class="list-unstyled">
        <% @pets.each do |pet| %>
        <% if pet.verified == true %>
          <li>
            <div class="well row <%= cycle('white-bg', '') %>">
              <div class="col-sm-12 text-center">
                <%= link_to controller: "users", action: "petshow", id: pet.id do %>
                  <%= image_tag "http://pets.neopets.com/cpn/" + pet.name + "/1/6.png", class: 'user-index-avatar' %>
                <% end %>
                <%= link_to controller: "users", action: "petshow", id: pet.id do %>
                  <h2 class="inline float-left"><%= pet.name %></h2>
                <% end %>
                <div class="float-right">
                  <% if pet.uft == true %>
                    <span class="label label-success">UFT</span>
                  <% end %>
                  <% if pet.ufa == true %>
                    <span class="label label-success">UFA</span>
                  <% end %>
                  <% if pet.uc == true %>
                    <span class="label label-success">UC</span>
                  <% end %>
                  <% if pet.rw == true %>
                    <span class="label label-success">RW</span>
                  <% end %>
                  <% if pet.rn == true %>
                    <span class="label label-success">RN</span>
                  <% end %>
                  <% if pet.hsd >= 250 %>
                    <span class="label label-success">BD</span>
                  <% elsif pet.hsd <= 249 && pet.hsd >= 100 %>
                    <span class="label label-success">St. BD</span>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
          <% end %>
        <% end %>
      </ul>
      <h4><%= will_paginate @pets, class: 'text-center' %></h4>
      <br/>
    </div>
  </div>
</div>

app/views/users/petshow.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <% if @pet.user %>
        <% if @pet.user.banned? %>
          <h1 class="text-center">Opps!</h4>
          <p class="text-center">This owner of this pet has been banned.  Nothing to see here, move along.</p>
        <% else %>
          <% if @pet.verified == true || admin_signed_in? || (user_signed_in? && @pet.user.id == current_user.id) %>
            <h4 class="text-center"><%= link_to user_path(@pet.user.id) do %><%= @pet.user.username %>'s<% end %> Pet</h4>
            <div class="well text-center">
              <div class="float-right">
                <% if @pet.uft == true %>
                  <span class="label label-success">UFT</span>
                <% end %>
                <% if @pet.ufa == true %>
                  <span class="label label-success">UFA</span>
                <% end %>
                <% if @pet.uc == true %>
                  <span class="label label-success">UC</span>
                <% end %>
                <% if @pet.rw == true %>
                  <span class="label label-success">RW</span>
                <% end %>
                <% if @pet.rn == true %>
                  <span class="label label-success">RN</span>
                <% end %>
                <% if @pet.hsd >= 250 %>
                  <span class="label label-success">BD</span>
                <% elsif @pet.hsd <= 249 && @pet.hsd >= 100 %>
                  <span class="label label-success">St. BD</span>
                <% end %>
              </div>
              <br/>
              <% link = "http://www.neopets.com/petlookup.phtml?pet=" + @pet.name %>
              <%= link_to image_tag("http://pets.neopets.com/cpn/" + @pet.name + "/1/5.png", class: 'pet-show-img'), link %>
              <h1><%= @pet.name %></h1>
              <h5><%= @pet.color %> <%= @pet.species %></h5>
              <h5><%= sanitize @pet.description, tags: %w(), attributes: %w() %></h5>
              <hr class="style-one"/>
              <% if @pet.hsd > 0 %>
                <% if @pet.level %>
                  <p>Level: <%= @pet.level %></p>
                <% end %>
                <% if @pet.hp %>
                  <p>Hit Points: <%= @pet.hp %></p>
                <% end %>
                <% if @pet.strength %>
                  <p>Strength: <%= @pet.strength %></p>
                <% end %>
                <% if @pet.defence %>
                  <p>Defence: <%= @pet.defence %></p>
                <% end %>
                <% if @pet.movement %>
                  <p>Movement: <%= @pet.movement %></p>
                <% end %>
                <p>HSD: <%= @pet.hsd %></p>
              <% end %>
              <% if admin_signed_in? %>
                <p><%= link_to "Edit Pet", {controller: "pets", action: "edit", user_id: @pet.user.id, id: @pet.id }, class: 'btn btn-primary' %>
                <%= link_to "Delete Pet", {controller: :pets, action: :destroy, user_id: @pet.user.id, id: @pet.id }, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger' %></p>
              <% else %>
                <% if user_signed_in? %>
                <% if current_user.id == @pet.user.id %>
                  <p><%= link_to "Edit Pet", {controller: "pets", action: "edit", user_id: @pet.user.id, id: @pet.id }, class: 'btn btn-primary' %>
                  <%= link_to "Delete Pet", {controller: :pets, action: :destroy, user_id: @pet.user.id, id: @pet.id }, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger' %></p>
                <% else %>
                  <%= link_to "Report Pet", new_report_path, class: 'btn btn-danger' %>
                <% end %>
              <% end %>
              <% end %>
            </div>
            <%= link_to "Back", :back %>
          <% else %>
            <h1 class="text-center">Opps!</h1>
            <p class="text-center">This pet is currently awaiting verification</p>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <% if @user.banned? %>
      <h1 class="text-center">Opps!</h4>
      <p class="text-center">This user has been banned.  Nothing to see here, move along.</p>
      <% else %>
      <div class="well text-center">
        <h1><%= @user.username %>'s Pets</h1>
        <h5><%= sanitize @user.profile.description, tags: %w(), attributes: %w() %></h5>
        <% unless @user.profile.neoname == "" || @user.profile.neoname == nil %>
          <% name = sanitize @user.profile.neoname, tags: %w(), attributes: %w() %>
          <% url = "http://www.neopets.com/userlookup.phtml?user=" + name %>
          <p>Neopets UN: <%= link_to name, url %></p>
        <% end %>
        <hr class="style-one"/>
        <% @pets.each do |pet| %>
          <% if pet.user_id == @user.id %>
            <% if pet.verified == true %>
              <div class="inline-pets">
                <%= link_to controller: "users", action: "petshow", id: pet.id do %>
                  <%= image_tag "http://pets.neopets.com/cpn/" + pet.name + "/1/6.png", class: 'user-index-avatar' %>
                <% end %>
              </div>
            <% elsif pet.verified == false && user_signed_in? && current_user.id == @user.id %>
               <div class="inline-pets">
                <%= link_to controller: "users", action: "petshow", id: pet.id do %>
                  <%= image_tag "http://pets.neopets.com/cpn/" + pet.name + "/1/6.png", class: 'user-index-avatar-red' %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        <br/>
        <% if user_signed_in? %>
          <% if current_user.id != @user.id %>
            <p>
            <%= link_to "Message me!", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: "post", class: 'btn btn-primary' %>
            <%= link_to "Report User", new_report_path, class: 'btn btn-danger' %>
            </p>
          <% end %>
          <% if current_user.id == @user.id %>
            <p><%= link_to "Edit Profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-primary' %></p>
          <% end %>
        <% end %>
        <% if admin_signed_in? %>
            <p><%= link_to "Edit Profile", edit_user_profile_path(user_id: @user.id), class: 'btn btn-primary' %>
            <%= link_to "Edit User", edit_user_path(id: @user.id), class: 'btn btn-primary' %></p>
        <% end %>
      </div>
      <%= link_to "Back", :back %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/verification.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Pet Trading Database Pets</h1>
      <p class="text-center">Pets awaiting verification</p>
      <p class="text-center"><b>NOTE:</b> Don't verify any UFA pets unless they have a deadline in their description.</p>
      <br/>
      <h4><%= will_paginate @pets, class: 'text-center' %></h4>
      <br>
      <ul class="list-unstyled">
        <% @pets.each do |pet| %>
        <% if pet.verified == false %>
          <li>
            <div class="well row <%= cycle('white-bg', '') %>">
              <div class="col-sm-12 text-center">
                <%= link_to controller: "users", action: "petshow", id: pet.id do %>
                  <%= image_tag "http://pets.neopets.com/cpn/" + pet.name + "/1/6.png", class: 'user-index-avatar' %>
                <% end %>
                <%= link_to controller: "users", action: "petshow", id: pet.id do %>
                  <h2 class="inline float-left"><%= pet.name %></h2>
                <% end %>
                <div class="float-right">
                  <% if pet.uft == true %>
                    <span class="label label-success">UFT</span>
                  <% end %>
                  <% if pet.ufa == true %>
                    <span class="label label-success">UFA</span>
                  <% end %>
                  <% if pet.uc == true %>
                    <span class="label label-success">UC</span>
                  <% end %>
                  <% if pet.rw == true %>
                    <span class="label label-success">RW</span>
                  <% end %>
                  <% if pet.rn == true %>
                    <span class="label label-success">RN</span>
                  <% end %>
                  <% if pet.hsd >= 250 %>
                    <span class="label label-success">BD</span>
                  <% elsif pet.hsd <= 249 && pet.hsd >= 100 %>
                    <span class="label label-success">St. BD</span>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
          <% end %>
        <% end %>
      </ul>
      <h4><%= will_paginate @pets, class: 'text-center' %></h4>
    </div>
  </div>
</div>