config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "www.pettp.com"
  root to: 'pages#home'
  devise_for :admins, controllers: { registrations: 'admins/registrations' }
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resource :pet
  end
  resources :admins do
    resource :profile
  end
  resources :conversations do
    resources :messages
  end
  get 'pets', to: 'users#petindex'
  get 'pets/:id' , to: 'users#petshow'
  get 'verification', to: 'users#verification'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  resources :reports
  get 'rules', to: 'pages#rules'
  get '/admins/sign_up' => redirect('pages#home')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetTP</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Exo:400,400i,700|Orbitron|Electrolize" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', type: 'text/javascript'%>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag("alienaishahead.png", class: "navbar-image") %>PetTP</a>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if admin_signed_in? %>
              <li><%= link_to "Reports", reports_path %></li>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Verify Pets", verification_path %></li>
              <li><%= link_to "Pets", pets_path %></li>
              <li><%= link_to "User Conversations", conversations_path %></li>
              <li><%= link_to "My Account", edit_admin_registration_path %></li>
              <li><%= link_to "Log Out", destroy_admin_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact Us", new_contact_path %></li>
            <% if user_signed_in? %>
              <% if current_user.profile %>
              <li><%= link_to "View Profile", user_path(id: current_user.id) %></li>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Pets", pets_path %></li>
              <li><%= link_to "Submit Pet", new_user_pet_path(user_id: current_user.id) %></li>
              <% if @unread != 0 %>
                <li><%= link_to "Messages", conversations_path %><div class="unread-cnt">(<%= @unread %>)</div></li>
              <% else %>
                <li><%= link_to "Messages", conversations_path %></li>
              <% end %>
              <% else %>
              <li><%= link_to "Create Profile", new_user_profile_path(user_id: current_user.id) %></li>
              <% end %>
              <li><%= link_to "My Account", edit_user_registration_path %></li>
              <li><%= link_to "Rules", rules_path %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log In", new_user_session_path %></li>
              <li class="link-divide">|</li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>